repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-json

  - repo: https://github.com/cathiele/pre-commit-rust
    rev: v0.1.0
    hooks:
      - id: cargo-fmt
      - id: cargo-clippy
        name: cargo-clippy rustypipe
        args: ["--package=rustypipe", "--tests", "--", "-D", "warnings"]
      - id: cargo-clippy
        name: cargo-clippy workspace
        args: ["--all", "--tests", "--features=rss,userdata,indicatif,audiotag", "--", "-D", "warnings"]
