name: CI
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  Test:
    runs-on: cimaster-latest
    services:
      warpproxy:
        image: thetadev256/warpproxy
        env:
          WARP_DEVICE_ID: ${{ secrets.WARP_DEVICE_ID }}
          WARP_ACCESS_TOKEN: ${{ secrets.WARP_ACCESS_TOKEN }}
          WARP_LICENSE_KEY: ${{ secrets.WARP_LICENSE_KEY }}
          WARP_PRIVATE_KEY: ${{ secrets.WARP_PRIVATE_KEY }}
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🦀 Setup Rust cache
        uses: https://github.com/Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: 📎 Clippy
        run: cargo clippy --all --tests --features=rss,indicatif,audiotag -- -D warnings

      - name: 🧪 Test
        run: |
          printf "$RUSTYPIPE_CACHE" > rustypipe_cache.json
          cargo nextest run --config-file ~/.config/nextest.toml --profile ci --retries 2 --features rss --workspace
        env:
          ALL_PROXY: "http://warpproxy:8124"
          RUSTYPIPE_CACHE: "${{ secrets.RUSTYPIPE_CACHE }}"
          YT_AUTHENTICATED: "${{ github.event_name != 'pull_request' }}" # no access to secrets for PRs

      - name: 💌 Upload test report
        if: always()
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: test
          path: target/nextest/ci/junit.xml

      - name: 🔗 Artifactview PR comment
        if: ${{ always() && github.event_name == 'pull_request' }}
        run: |
          if [[ "$GITEA_ACTIONS" == "true" ]]; then RUN_NUMBER="$GITHUB_RUN_NUMBER"; else RUN_NUMBER="$GITHUB_RUN_ID"; fi
          curl -SsL --fail-with-body -w "\n" -X POST https://av.thetadev.de/.well-known/api/prComment -H "Content-Type: application/json" \
            --data '{"url": "'"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$RUN_NUMBER"'", "pr": ${{ github.event.number }}, "artifact_titles": {"test":"🧪 Test report"}, "artifact_paths": {"test":"/junit.xml?viewer=1"}}'
