name: CI
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  Test:
    runs-on: cimaster-latest
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🦀 Setup Rust cache
        uses: https://github.com/Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: 📎 Clippy
        run: cargo clippy --all --features=rss -- -D warnings

      - name: 🧪 Test
        run: cargo nextest run --config-file ~/.config/nextest.toml --profile ci --retries 2 --features rss --workspace

      - name: 💌 Upload test report
        if: always()
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: test
          path: target/nextest/ci/junit.xml

      - name: 🔗 Artifactview PR comment
        if: ${{ always() && github.event_name == 'pull_request' }}
        run: |
          if [[ "$GITEA_ACTIONS" == "true" ]]; then RUN_NUMBER="$GITHUB_RUN_NUMBER"; else RUN_NUMBER="$GITHUB_RUN_ID"; fi
          curl -SsL --fail-with-body -w "\n" -X POST https://av.thetadev.de/.well-known/api/prComment -H "Content-Type: application/json" \
            --data '{"url": "'"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$RUN_NUMBER"'", "pr": ${{ github.event.number }}}'
