name: CI
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  Test:
    runs-on: cimaster-latest
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4
      - name: 🦀 Setup Rust cache
        uses: https://github.com/Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: 📎 Clippy
        run: cargo clippy --all --features=rss -- -D warnings

      - name: 🧪 Test
        run: cargo test --features=rss --workspace
