name: Release
on:
  push:
    tags:
      - "*/v*.*.*"

jobs:
  Release:
    runs-on: cimaster-latest
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v3

      - name: Get variables
        run: |
          git fetch --tags --force #the checkout action does not load the tag message

          echo "CRATE=$(echo '${{ github.ref_name }}' | awk 'BEGIN{RS="/"} NR==1{print}')" >> "$GITHUB_ENV"
          echo "CRATE_VERSION=$(echo '${{ github.ref_name }}' | awk 'BEGIN{RS="/"} NR==2{print}')" >> "$GITHUB_ENV"
          {
            echo 'CHANGELOG<<END_OF_FILE'
            git show -s --format=%N "${{ github.ref_name }}" | tail -n +4 | awk 'BEGIN{RS="-----BEGIN PGP SIGNATURE-----"} NR==1{printf $0}'
            echo END_OF_FILE
          } >> "$GITHUB_ENV"

      - name: 📤 Publish crate
        run: |
          mkdir -p ~/.cargo
          printf '[registries.thetadev]\nindex = "https://code.thetadev.de/ThetaDev/_cargo-index.git"\ntoken = "Bearer ${{ secrets.TOKEN_GITEA }}"\n' >> ~/.cargo/config.toml
          cargo publish --registry thetadev --package "${{ env.CRATE }}"

      - name: 🎉 Publish release
        uses: https://gitea.com/actions/release-action@main
        with:
          title: "${{ env.CRATE }} ${{ env.CRATE_VERSION }}"
          body: "${{ env.CHANGELOG }}"
