[package]
name = "rustypipe-cli"
version = "0.1.0"
edition = "2021"
authors = ["ThetaDev <t.testboy@gmail.com>"]
license = "GPL-3.0"
description = "CLI for RustyPipe - download videos and extract data from YouTube / YouTube Music"
keywords = ["youtube", "video", "music"]
categories = ["multimedia"]

[features]
default = ["rustls-tls-native-roots"]

# Reqwest TLS options
native-tls = [
    "reqwest/native-tls",
    "rustypipe/native-tls",
    "rustypipe-downloader/native-tls",
]
native-tls-alpn = [
    "reqwest/native-tls-alpn",
    "rustypipe/native-tls-alpn",
    "rustypipe-downloader/native-tls-alpn",
]
native-tls-vendored = [
    "reqwest/native-tls-vendored",
    "rustypipe/native-tls-vendored",
    "rustypipe-downloader/native-tls-vendored",
]
rustls-tls-webpki-roots = [
    "reqwest/rustls-tls-webpki-roots",
    "rustypipe/rustls-tls-webpki-roots",
    "rustypipe-downloader/rustls-tls-webpki-roots",
]
rustls-tls-native-roots = [
    "reqwest/rustls-tls-native-roots",
    "rustypipe/rustls-tls-native-roots",
    "rustypipe-downloader/rustls-tls-native-roots",
]

[dependencies]
rustypipe.workspace = true
rustypipe-downloader.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
futures.workspace = true
serde.workspace = true
serde_json.workspace = true

indicatif.workspace = true
anyhow.workspace = true
clap.workspace = true
tracing-subscriber.workspace = true
serde_yaml.workspace = true
dirs.workspace = true
