[package]
name = "rustypipe-cli"
version = "0.4.0"
rust-version = "1.70.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "CLI for RustyPipe - download videos and extract data from YouTube / YouTube Music"

[features]
default = ["native-tls"]

# Reqwest TLS options
native-tls = [
    "reqwest/native-tls",
    "rustypipe/native-tls",
    "rustypipe-downloader/native-tls",
]
native-tls-alpn = [
    "reqwest/native-tls-alpn",
    "rustypipe/native-tls-alpn",
    "rustypipe-downloader/native-tls-alpn",
]
native-tls-vendored = [
    "reqwest/native-tls-vendored",
    "rustypipe/native-tls-vendored",
    "rustypipe-downloader/native-tls-vendored",
]
rustls-tls-webpki-roots = [
    "reqwest/rustls-tls-webpki-roots",
    "rustypipe/rustls-tls-webpki-roots",
    "rustypipe-downloader/rustls-tls-webpki-roots",
]
rustls-tls-native-roots = [
    "reqwest/rustls-tls-native-roots",
    "rustypipe/rustls-tls-native-roots",
    "rustypipe-downloader/rustls-tls-native-roots",
]

[dependencies]
rustypipe = { workspace = true, features = ["rss"] }
rustypipe-downloader.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true

indicatif.workspace = true
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde_yaml.workspace = true
dirs.workspace = true

anstream = "0.6.15"
owo-colors = "4.0.0"
const_format = "0.2.33"
