name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      warpproxy:
        image: thetadev256/warpproxy
        env:
          WARP_DEVICE_ID: ${{ secrets.WARP_DEVICE_ID }}
          WARP_ACCESS_TOKEN: ${{ secrets.WARP_ACCESS_TOKEN }}
          WARP_LICENSE_KEY: ${{ secrets.WARP_LICENSE_KEY }}
          WARP_PRIVATE_KEY: ${{ secrets.WARP_PRIVATE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Download rustypipe-botguard
        run: |
          TARGET=$(rustc --version --verbose | grep "host:" | sed -e 's/^host: //')
          cd ~
          curl -SsL -o rustypipe-botguard.tar.xz "https://codeberg.org/ThetaDev/rustypipe-botguard/releases/download/v0.1.1/rustypipe-botguard-v0.1.1-${TARGET}.tar.xz"
          cd /usr/local/bin
          sudo tar -xJf ~/rustypipe-botguard.tar.xz
          rm ~/rustypipe-botguard.tar.xz
          rustypipe-botguard --version

      - name: Clippy
        run: |
          cargo clippy --all --tests --features=rss,userdata,indicatif,audiotag -- -D warnings
          cargo clippy --package=rustypipe --tests -- -D warnings
          cargo clippy --package=rustypipe-downloader -- -D warnings
          cargo clippy --package=rustypipe-cli -- -D warnings
          cargo clippy --package=rustypipe-cli --features=timezone -- -D warnings

      - name: Test
        run: cargo nextest run --config-file nextest.toml --profile ci --retries 2 --features rss,userdata --workspace -- --skip 'user_data::'
        env:
          ALL_PROXY: "http://warpproxy:8124"

      - name: Move test report
        if: always()
        run: mv target/nextest/ci/junit.xml junit.xml || true

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: |
            junit.xml
            rustypipe_reports

      - name: Artifactview PR comment
        if: always() && github.event_name == 'pull_request'
        run: |
          curl -SsL --fail-with-body -w "\n" -X POST https://av.thetadev.de/.well-known/api/prComment -H "Content-Type: application/json" \
            --data '{"url": "'"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"'", "pr": ${{ github.event.number }}, "artifact_titles": {"test":"Test report"}, "artifact_paths": {"test":"/junit.xml?viewer=1"}}'
